### ISSUE TITLE
iron-overlay-closed event doc is garbled

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-overlay-behavior#103]
https://elements.polymer-project.org/elements/iron-overlay-behavior#event-iron-overlay-closed

    * @param {{canceled: (boolean|undefined)}} set to the `closingReason` attribute

Not sure exactly what this is supposed to look like. The description isn't really helpful.

I'm not sure whether the @param tag to an event should assume that the parameters are all passed in the detail object, or whether they may be added directly to the event object. (Maybe @garlicnation can help out here?)

In the first case, this should probably be:

    * @param {boolean|undefined} cancelled Whether the overlay was cancelled.

In the latter case, I think it should be something like:

    * @param {{canceled: (boolean|undefined)}} detail Set to the `closingReason` object.

Also, we really need to work on formatting those closure type definitions better in the output. They are fugly.

**Comment by tuct** [comment]
As custom events are fired with fire function: https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html
It make sense to document the details object.

So i think 
`* @param {{canceled: (boolean|undefined)}} detail Set to the closingReason object.`
is right because the detail object is not a primitive and must therefore be annotated like it is, see:
https://www.polymer-project.org/1.0/tools/documentation.html#properties

+1 for changing the description 
`* @param {{canceled: (boolean|undefined)}} canceled Whether the overlay was cancelled.`
