### ISSUE TITLE
a button with onclick="overlay.close()" will close all opened overlays

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-overlay-behavior#109]
Here the example: Close overlay 2, overlay 1 should still be opened but instead gets closed
http://jsbin.com/xuguxa/1/edit?html,output

**Comment by tuct** [comment]
Only if the close button is outside of the other overlays.  Like in your example, closing overlay 2 will not close overlay 1 because overlay 1 is within the boundaries of overlay 2. Otherwise clicking anywhere on  overlay 2 or other where outside of overlay 1 will trigger a close of it. 

I hope you see my point. 

I guess when clicking outside is disabled for the overlays the use case would be possible. (or by checking the original event in the beforeonclose function for a click triggered by a overlay close button)

**Comment by tuct** [comment]
Here is an example: http://jsbin.com/yewagaxeta/edit?html,output

**Comment by valdrinkoshi** [comment]
Yes you're right, but `no-cancel-on-outside-click` also prevents from closing the overlay by clicking anywhere else in the `document`. I believe that we shouldn't encourage people to nest overlays or to use `no-cancel-on-outside-click`, but rather check (maybe through in the `iron-overlay-manager`) if you clicked in another overlay. In that case only close the overlay on top (`currentOverlay`).

**Comment by tuct** [comment]
Sounds like a good solution approach, is there a function to close all currently opened overlays? This would be handy in such a case.

**Comment by valdrinkoshi** [comment]
No we don't have it, but it would be a nice public method to be added to `IronOverlayManager`.

**Comment by valdrinkoshi** [comment]
@tuct a function to close all overlays would be something as simple as
```javascript
var overlay; 
while(overlay = Polymer.IronOverlayManager.currentOverlay()){
 overlay.close();
}
```
http://jsbin.com/qoxati/4/edit?html,output

**Comment by tuct** [comment]
Before we invest more into this topic we should find out if supporting nested overlays is a valid use case or not? First question is if any other iron or paper components use the overlay nested or not. If not we should definitely what for a valid real world example/use case.

**Comment by valdrinkoshi** [comment]
Nested overlays are needed for things like a `paper-menu-button` (which has an `iron-dropdown` in it) inside a `paper-dialog`.

**Comment by valdrinkoshi** [comment]
Also, this issue happens with non-nested overlays. In the provided example the 2 overlays are siblings.
