### ISSUE TITLE
Auto refitting.

### ISSUE THREAD

**Issue by kysonic** [PolymerElements/iron-overlay-behavior#121]
Hi everybody! My paper-dialog contains component based on iron-dropdown. When i try open the dropdown the paper-dialog make a leap because of iron-overlay-behavior's auto refitting. Check this link to see it 

[https://drive.google.com/file/d/0B7mZeGEPaFYLZmhFaDdERzZYRTQ/view](https://drive.google.com/file/d/0B7mZeGEPaFYLZmhFaDdERzZYRTQ/view)

**Comment by valdrinkoshi** [comment]
That's odd :x Could you provide a simplified jsbin to reproduce the issue? There are some PRs that might already address it.

**Comment by kysonic** [comment]
Yeah. I've made one PR regarding this issue... Anyway i've made fiddle providing representation of problem i met: 

[http://jsfiddle.net/kysonic/rt4vzkzs/2/ ](http://jsfiddle.net/kysonic/rt4vzkzs/2/ )

Open this fiddle, open dialog and click on the paper-input. You will be able to notice small leap of a paper-dialog. If you reopen the paper-dialog a problem will disappear. But if you refresh a page, it will appear again. 

How far i understand when iron-dropdown is opening iron-overlay-behavior registers resize of dialog and after this it invokes "refit()" function.

**Comment by valdrinkoshi** [comment]
I don't see the "jump" on mac:
![no-bug](https://cloud.githubusercontent.com/assets/6173664/13612210/15c4848c-e51b-11e5-9695-2cd50c4604db.gif)
I tried on windows and I do see the "jump". I'll further investigate on this, but I suspect this is caused by the `overflow` style of `iron-dropdown` after animating.

In general, consider declaring all your overlays as children of `body` (`iron-dropdown` included), e.g. http://jsbin.com/nahato/5/edit?html,output This will save you from any stacking context issues too ;)

**Comment by valdrinkoshi** [comment]
I confirm that this is caused by `iron-dropdown` animations, in fact if I disable them it works properly also on windows
http://jsbin.com/hewidar/3/edit?html,output
![yes-bug](https://cloud.githubusercontent.com/assets/6173664/13613039/34b49e3c-e51f-11e5-9b19-d02426d168f8.gif)

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-dropdown#69
