### ISSUE TITLE
Wrong backdrop z-index for multiple overlays

### ISSUE THREAD

**Issue by r0l1** [PolymerElements/iron-overlay-behavior#124]
If multiple dialogs are opened with a backdrop, then the backdrop should update its z-index to overlay all previous dialogs.

**Demonstration:**

Use the demo source in the demo/index.html file and adjust the "Multiple overlays can be opened" sample, by adding the _with-backdrop_ attribute to both overlays:

``` html
<h3>Multiple overlays can be opened.</h3>
<demo-snippet>
<template>
  <button onclick="multiple.open()">Open first overlay</button>
  <simple-overlay id="multiple" tabindex=-1 with-backdrop>
    <p>click to open another overlay</p>
    <button onclick="multiple2.open()">Open second overlay</button>
    <button onclick="multiple.close()">Close this</button>
  </simple-overlay>
  <simple-overlay id="multiple2" tabindex=-1 with-backdrop>
    <h2>Hi!</h2>
    <button onclick="multiple2.close()">Close</button>
  </simple-overlay>
</template>
</demo-snippet>
```

**Comment by m4ng0squ4sh** [comment]
Hmm, I understand. However I do think, there should be an option available to set this specific behaviour. Imagine an open dialog displaying some data. Data manipulation is triggered by the user and a confirmation message box pops up. The backdrop overlaying the previous dialog is strictly required.Otherwise the user would be able to trigger further data manipulations on the dialog underneath, although the message box is still visible.

An additional attribute to trigger this behaviour would be fantastic:

```html
<simple-overlay with-backdrop attached-backdrop>
</simple-overlay>

<!-- OR -->

<simple-overlay with-backdrop sticky-backdrop>
</simple-overlay>

<!-- OR -->

<simple-overlay with-backdrop pin-backdrop>
</simple-overlay>
```

What do you think?

**Comment by valdrinkoshi** [comment]
Uhm, there is another feature request for a new property `always-on-top` https://github.com/PolymerElements/iron-overlay-behavior/issues/3
Maybe that could be used together with `with-backdrop` to have the overlay with `always-on-top` to be on top of the others & the backdrop element too.

I wonder though if the backdrop should be always behind the top overlay by default.

**Comment by m4ng0squ4sh** [comment]
Sounds good. Could you explain the functionality of #3 in detail? There is no description and I didn't understand the full context of `always-on-top`. I would then work on it and provide a pull request. I really need this feature soon and I don't want to hack around this problem...

> I wonder though if the backdrop should be always behind the top overlay by default.

It definitively should be! This is the default behaviour everyone would expect and common CSS frameworks as bootstrap, foundation,... all mimic this.

**Comment by valdrinkoshi** [comment]
Sure, I'll provide more details for #3 directly there.

About the z-index of the backdrop, I think we should make this change anyways, since this is more a bug than a feature. The top element with backdrop should drive the z-index of the backdrop.
If a user wants to obtain something like this (current :
```
overlay 2 (on top)
overlay 1
backdrop
```
Then he should set `overlay2.withBackdrop = false; overlay1.withBackdrop = true`

The change should be trivial, only change the method `_overlayWithBackdrop` to loop from last to first
https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L185

**Comment by valdrinkoshi** [comment]
Technically, this would be a breaking change, so it could not be merged in `iron-overlay-behavior v1.x`

**Comment by valdrinkoshi** [comment]
Here a solution for `iron-overlay-behavior 1.x`, it consists in waiting for the overlay to be opened and then setting the `z-index` to the backdrop element http://jsbin.com/getixu/2/edit?html,output

**Comment by MartinsThiago** [comment]
Houston... we still have a problem

![image](https://cloud.githubusercontent.com/assets/8419829/24919006/b4ec6bc4-1eb8-11e7-844b-5810d3f3dec4.png)

Polymer: v1.8.1
iron-overlay-behavior: v1.10.4

**Comment by valdrinkoshi** [comment]
@MartinsThiago  to solve that issue, we'd have to reparent the overlay and its content into `<body>` or any other stacking-context-safe node. This would be a breaking change because:
- style encapsulation won't apply
- attach/detach/attach will lead to poor performance
- query selectors and events would fire from a different tree branch than where you declare originally your overlay

In 2.0, we want to keep our elements and behaviors hybrid (they will work seamlessly with Polymer 1.x and 2.x), so that our users can transition to Web Components v1 at their own pace.
This means `iron-overlay-behavior 2.x` won't introduce breaking changes.

There won't be a `iron-overlay-behavior 3.x`, but rather a new element which tackles this issue. I've already worked on this element, [`<iron-overlay>`](https://github.com/PolymerLabs/iron-overlay), which is a new overlay system that can afford to make those breaking changes.
Your feedback is more than welcome :)

**Comment by bennypowers** [comment]
I've used this hack to extract elements to the app-shell and reposition them when closing. YMMV.

```js
// my-app.js
_handleIronOverlayOpened: function(e) {
  let modal = e.path ? e.path[0] : e.target;
      modal._cachedParentNode = modal.parentNode;
      modal._cachedDomHost = modal.domHost;
   let app = document.body.querySelector('eve-app');
   if (modal.withBackdrop && modal.domHost != app) { // HACK: https://github.com/PolymerElements/iron-overlay-behavior/issues/124
     app.shadowRoot.appendChild(modal);
   }
},

_handleIronOverlayClosed: function(e) {
  let modal = e.path ? e.path[0] : e.target;
  if (modal.withBackdrop && !modal._cachedDomHost == this) {
    modal._cachedParentNode.appendChild(modal);
  }
  if (modal.localName === 'element-to-reset') {
   modal.reset();
  }
},
```

**Comment by valdrinkoshi** [comment]
I just noticed that if an overlay w/o backdrop is opened **after** one with backdrop, it is rendered on top of it, which is the same effect as when it has a backdrop too.
I think that the backdrop z-index should be updated to be below the top-most overlay with backdrop.
