### ISSUE TITLE
Demo does not work for scrolling overlay in landscape mode

### ISSUE THREAD

**Issue by joeblew99** [PolymerElements/iron-overlay-behavior#206]
The demo running on the polymer elements web site.
The overlay does not centre vertically when in landscape.

Environment context:
Android Nexus 6, latest standard android.
Chrome browser

**Comment by valdrinkoshi** [comment]
Hi @joeblew99, All the overlays are not centered, because the demo is contained in an `iframe` hence the overlay can be centered only within the iframe https://elements.polymer-project.org/elements/iron-overlay-behavior?view=demo:demo/index.html&active=Polymer.IronOverlayBehavior

If you open the demo page by itself you should see them centered https://elements.polymer-project.org/bower_components/iron-overlay-behavior/demo/index.html

**Comment by valdrinkoshi** [comment]
The demo should be adjusted anyways, since the scrolling content goes outside the window when on landscape.
