### ISSUE TITLE
Backdrop in front of overlay on iOS

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/iron-overlay-behavior#208]
### Description

If an overlay (e.g. an paper-dialog) is inside an paper-header-panel, the backdrop is in front of the overlay on iOS safari.
### Expected outcome

Backdrop is behind the overlay.
### Actual outcome

Backdrop is in front of the overlay.
### Live Demo

https://jsbin.com/mopahuruje/1/edit?html,output

Looks like html imports are not working in safari, so the jsbin example is vulcanized.
### Browsers Affected

Safari on iOS, (Safari on OS X is not affected)

**Comment by bwh-rl** [comment]
Debugged this, this is not an JS issue, iron-overlay-manager's trackBackdrop method is assigning the correct z-index.

It looks like the z-index breaks due the flex layout used in the paper-header-panel.

**Comment by bwh-rl** [comment]
It's not the flex layout, the bug is triggered by the overflow properties.
https://jsbin.com/mawukekice/5/edit?html,output

**Comment by valdrinkoshi** [comment]
Hi @bwh-rl, 
This issue has already been reported [many, many times](https://github.com/PolymerElements/paper-dialog/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22stacking%20context%22)...Unfortunately this is a known limitation of overlays, which are stacking-context-sensitive. From [iron-overlay-behavior documentation](https://elements.polymer-project.org/elements/iron-overlay-behavior):
> You must ensure no element has a stacking context with a higher z-index than its parent stacking context. You should place this element as a child of &lt;body&gt; whenever possible.

This is due to how [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) works: any element that creates a new stacking context will "trap" all its children within it (overlays included), [try it yourself](http://jsbin.com/lemufe/4/edit?html,output).

**Comment by bwh-rl** [comment]
As "whenever possible" indicates, it's not always possible.
I'm working on a bigger app and got the content separated into elements.

So the way this should be done is to put all overlays of the complete app out of their related view elements and but them all in the body?

Since i handle the scrollable area inside of most content elements manual via applying the --layout-scroll mixin, i have removed the -webkit-overflow-scrolling property.

Maybe the documentation should be more detailed on this issue.

**Comment by valdrinkoshi** [comment]
Unfortunately this is a limitation of the platform, as we don't have a way to go outside a stacking context. Even if the backdrop is put inside the overlay, if the parent creates a stacking context it would crop all its children, [see this example](http://jsbin.com/nopujef/3/edit?html,output).
One could use the [`<dialog>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog), but it works only on Chrome & Opera.
There is a polyfill for that, but it has [the same limitations](https://github.com/GoogleChrome/dialog-polyfill#limitations).

I'm working on overlay 2.0 where the main idea is to give a mechanism to declare overlays wherever in the document, but they'll be "stamped" in a stacking-context-safe place. Here you can see one experiment https://github.com/PolymerElements/iron-overlay-behavior/pull/155

**Comment by bwh-rl** [comment]
Overlay 2.0 sounds like the optimal solution, you could then use the stacking context instead of beeing affected by it.
Since overlay is the only element demanding z-indexes over the whole APP, elements like drawer panel could create their own stacking context which would allow users to use z-index inside the content without e.g. overlapping the scrim.
Would also make hardly comprehensible z-indexes like 153 needless, because the overlay would be in its own stacking context.

e.g. simplified
```html
<body>
  <poly-main style="z-index:1">
    <drawer-panel>
      <drawer style="z-index:1"></drawer>
      <scrim style="z-index:2"></scrim>
      <main style="z-index:3">
        <!-- nothing here could pierce scrim or the drawer, regardless of the z-index. -->
      </main>
    <drawer-panel>
  </poly-main>
  <poly-overlay style="z-index:2">
  </poly-overlay>
</body>
```

**Comment by rene-lindner-isw** [comment]
Any news on overlay 2.0? In paper-dialog#2.0-preview this issue is still present.

**Comment by valdrinkoshi** [comment]
To solve this issue, we'd have to reparent the overlay and its content into `<body>` or any other stacking-context-safe node. This would be a breaking change because:
- style encapsulation won't apply
- attach/detach/attach will lead to poor performance
- query selectors and events would fire from a different tree branch than where you declare originally your overlay

In 2.0, we want to keep our elements and behaviors hybrid (they will work seamlessly with Polymer 1.x and 2.x), so that our users can transition to Web Components v1 at their own pace.
This means `iron-overlay-behavior 2.x` won't introduce breaking changes.

There won't be a `iron-overlay-behavior 3.x`, but rather a new element which tackles this issue. I've already worked on this element, [`<iron-overlay>`](https://github.com/PolymerLabs/iron-overlay), which is a new overlay system that can afford to make those breaking changes.
Your feedback is more than welcome :)

For this particular issue: even if we'd duplicate backdrops in each overlay, you'd still have problems with the stacking context trapping the overlay e.g. try this http://jsbin.com/xacuqi/2/edit?html,output - the overlay is trapped on the left panel

**Comment by rene-lindner-isw** [comment]
Due the z-indexes used by app-drawer-layout and app-header layout this issue gets even more present.

You just can't use an modal paper-dialog inside an app-drawer-layout or app-header layout.
Means you can't use a modal paper-dialog inside an polymer-starter-kit view.

Though i'm aware that the problem is complex and there is no simple solution.
The new approach looks promising :).

For our usecases I've build an workshift solution to use till the new iron-overlay is finished.
Build an remote-element that can control an stacking-context safe positioned dialog.
Needs extra markup, and no content manipulation is possible, but for now it fits our usecases.

https://github.com/rene-lindner-isw/isw-dialog

Feedback would be highly appreciated.

**Comment by rwestlund** [comment]
@rene-lindner-isw  I've implemented something similar in my applications.

I group all my dialogs in a custom element outside the `app-layout` elements and I use `iron-signals` to communicate with it from various points in my app.  In the "please open dialog x for me" events I include data to fill the form or dialog, a reference to `this` (the requesting element), and the name of a callback function that should be called on the requesting element once the form is closed.  In this way, the requesting element still gets the `function(e, reason)` callback it normally would.

I'm quite happy with this solution, as I only have one global copy of every dialog/form rather than one inside every element that uses it.  For example, I only have one form for editing users, rather than one inside each of my user display elements.

**Comment by valdrinkoshi** [comment]
FYI I've started a discussion on this problem here to see what help we can get from the platform on this issue https://github.com/whatwg/html/issues/2525

**Comment by rene-lindner-isw** [comment]
Published the element on webcomponents.org - https://www.webcomponents.org/element/IswPolymerElements/isw-dialog

@valdrinkoshi if you have some time, could you may take a look at it and give me some feedback?
