### ISSUE TITLE
IronOverlayManager should skip elements that have noCancelOnOutsideClick/Esc when a close event is handled

### ISSUE THREAD

**Issue by helenxywu** [PolymerElements/iron-overlay-behavior#212]
### Description

An overlay with noCancelOnOutsideClick prevents all overlays without cancel to stay open. 
Example:
There are two overlays. A dropdown opens and a user does an action on the dropdown triggering a toast to open. The toast has noCancelOnOutsideClick = true, but the dropdown should close on outside click or esc key. 
### Expected outcome

The dropdown stays open when the user clicks outside of the dropdown for as long as the toast is open.
### Actual outcome

The dropdown should close when the user clicks outside of it, but the toast should remain until it closes (in this case after a few seconds). The manager should skip elements that have noCancel on them, and cancel the next overlay that has noCancel = false.

**Comment by valdrinkoshi** [comment]
@helenxywu, the current implementation delegates the click handling (same for esc, tab, and focus events) to the `currentOverlay` (aka the last opened overlay). Changing this would be a breaking change, e.g. see this example http://jsbin.com/yefuda/3/edit?html,output (try uncommenting the other `<base>`).
We're missing a way to delegate the event handling to the next overlay.

Can you ensure the `paper-toast` is opened before the dialog? If not, a possible workaround is bring the previous overlay on top again with `this._manager.addOverlay(previousOverlay)`e.g. see http://jsbin.com/piziku/3/edit?html,output

**Comment by valdrinkoshi** [comment]
The current behavior works well in scenarios like the following: user opens a dropdown menu, then a modal dialog. If she/he clicks outside the modal dialog, the dropdown menu should still stay opened.  Changing this behavior would be a breaking change for these users http://jsbin.com/givitok/2/edit?html,output

In other use cases we'd want to delegate the handling of click to the overlay that can handle them e.g. http://jsbin.com/yefuda/4/edit?html,output if the user opens a dialog and then a toast, when she/he clicks outside the toast, the dialog should close, because the toast, even if is the top overlay, doesn't close on click outside (it has `noCancelOnOutsideClick = true` by default)

**Comment by valdrinkoshi** [comment]
This could be solved by introducing a new property `allowClickThrough` which would be used by `IronOverlayManager` to execute `_onCaptureClick` on the following overlays.
