### ISSUE TITLE
autofocus does not work in Firefox

### ISSUE THREAD

**Issue by aigan** [PolymerElements/iron-overlay-behavior#238]
### Description
autofocus does not work in Firefox.

I replaced _focusNode with a working version. Replaceing
  `Polymer.dom(this).querySelector('[autofocus]')`
with
  `this.querySelector('[autofocus]')`

The focus will not work without that fix.

### Expected outcome
Focus should be set to the autofocus element in a iron-overlay-behavior component.

### Actual outcome
The search fo autofocus fails and it falls back to default.

### Live Demo
Working version:
http://jsbin.com/hagiqeq/edit?html

Not working:
http://jsbin.com/gadibu/edit?html

### Steps to reproduce

1. Open http://output.jsbin.com/hagiqeq in firefox and try typing to verify that the input field has focus.

2. Open http://output.jsbin.com/gadibu in firefox and try typing to verify that the input field does not have focus.

### Browsers Affected

- [ ] Chrome
- [x] Firefox

**Comment by valdrinkoshi** [comment]
The behavior autofocuses distributed content by design. If you want to change this behavior, its totally legit to override the `_focusNode` getter as you're doing.
In your example, your element wants to autofocus a node contained in the shadowRoot: to achieve that, you should override `_focusNode` like this:
```js
get _focusNode(){
  return this._focusedChild || Polymer.dom(this.root).querySelector('[autofocus]') || this;
}
```
or just assign an id to the autofocusable node and refer to it using `this.$.autofocusNode`, e.g.
```html
<template>
  <input type="text" id="autofocusNode">
  <!--- ... -->
</template>
<script>
  // ...
  get _focusNode(){
    return this._focusedChild || this.$.autofocusNode;
  }
```
