### ISSUE TITLE
Backdrop not attached for Polymer v2

### ISSUE THREAD

**Issue by ifahrentholz** [PolymerElements/iron-overlay-behavior#242]
### Description

The `simple-overlay with-backdrop` does not attach the backdrop markup to the DOM.

### Usage:
`<v2-overlay id="backdrop" with-backdrop></v2-overlay>`

### Element markup:
```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/iron-overlay-behavior/iron-overlay-behavior.html">

<dom-module id="v2-overlay">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h2>Hello [[prop1]]!</h2>
    <button on-click="_handleClose">close</button>
  </template>

  <script>
    /** @polymerElement */
    class V2Overlay extends Polymer.mixinBehaviors([Polymer.IronOverlayBehavior], Polymer.Element) {
      static get is() { return 'v2-overlay'; }
      
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'v2-overlay'
          },
        }
      }
          
      _handleClose() {
        this.close();
      }
    }

    window.customElements.define(V2Overlay.is, V2Overlay);
  </script>
</dom-module>
```

**I've also tried to use the property directly - without success:** 
```
static get properties() {
  return {
    withBackdrop: {
      type: Boolean,
      value: true
    },
    prop1: {
      type: String,
      value: 'v2-overlay'
    },
  }
}
```

### Actual outcome

The `with-backdrop` prop is not considered.

**Comment by valdrinkoshi** [comment]
Looks like working as expected, tested with `v2.0.0` http://jsbin.com/civeberugo/2/edit?html,output
Let me know if the problem persists 👌

**Comment by dsanders11** [comment]
@valdrinkoshi, this is not fixed if you use @ifahrentholz's actual code. [Here's a JSBin with his code](http://jsbin.com/lomepezozi/1/edit?html,output).

It's the same implementation style that the [Polymer shop demo uses](https://github.com/Polymer/shop/blob/master/src/shop-cart-modal.html) which is why both he and I have tried to implement it in our own code with no success now. The backdrop is created but it has an empty slot, and the content is shown behind the backdrop. It's unclear why this doesn't work, and the docs for `iron-overlay-behavior` don't have an example of using it in this way, even though this seems to be an intuitive way to use it, rather than making a separate `simple-overlay` element and then filling that.

**Comment by valdrinkoshi** [comment]
That's because you didn't style the overlay to have a background color, e.g. see the same jsbin with a background-color and padding added to the overlay host
http://jsbin.com/joyevo/1/edit?html,output
