### ISSUE TITLE
z-index overrides are potentially fragile

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/iron-overlay-behavior#40]
Maybe this is a no-op, but if you override z-index of the overlay-backdrop using:

```
 --iron-overlay-backdrop: { z-index: 1000; }
```
Wont this throw off the z-index calculations in -manager which always starts at 10?

**Comment by valdrinkoshi** [comment]
Fair point, here a jsbin showing the issue
http://jsbin.com/qosiqix/4/edit?html,output

**Comment by valdrinkoshi** [comment]
`Polymer.IronOverlayManager` provides the [ensureMinimumZ](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L197) method that you could use to ensure all overlays have a minimum z-index http://jsbin.com/riwisab/2/edit?html,output

If you want to target only the overlays with backdrop, you can set the z-index to these overlays instead of the backdrop http://jsbin.com/pigaduw/1/edit
